version: '3.3'
services: 
    api-service:
        build: ./
        volumes: 
            - ./:/usr/src/app/
        ports: 
            - "5000:5000"
        restart: always
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
